// This file is autogenerated. Do not modify.

@objc class Strings : NSObject {

	@objc class Accessibility : NSObject {

		@objc class LeftDrawer : NSObject {

			@objc static var profileHint = OEXLocalizedString("ACCESSIBILITY.LEFT_DRAWER.PROFILE_HINT", nil)
			@objc static func profileLabel(userName : String, userEmail : String) -> String { return OEXLocalizedString("ACCESSIBILITY.LEFT_DRAWER.PROFILE_LABEL", nil).oex_format(withParameters: ["user_name" : userName, "user_email" : userEmail]) }

		}
		@objc class Whatsnew : NSObject {

			@objc static var closeLabel = OEXLocalizedString("ACCESSIBILITY.WHATSNEW.CLOSE_LABEL", nil)
			@objc static func headerLabel(appVersion : String) -> String { return OEXLocalizedString("ACCESSIBILITY.WHATSNEW.HEADER_LABEL", nil).oex_format(withParameters: ["app_version" : appVersion]) }

		}


		@objc static func browserBySubjectHint(subjectName : String) -> String { return OEXLocalizedString("ACCESSIBILITY.BROWSER_BY_SUBJECT_HINT", nil).oex_format(withParameters: ["subject_name" : subjectName]) }
		@objc static var bulkDownloadDownloadedHint = OEXLocalizedString("ACCESSIBILITY.BULK_DOWNLOAD_DOWNLOADED_HINT", nil)
		@objc static var bulkDownloadDownloadingHint = OEXLocalizedString("ACCESSIBILITY.BULK_DOWNLOAD_DOWNLOADING_HINT", nil)
		@objc static var bulkDownloadHint = OEXLocalizedString("ACCESSIBILITY.BULK_DOWNLOAD_HINT", nil)
		@objc static var closeHint = OEXLocalizedString("ACCESSIBILITY.CLOSE_HINT", nil)
		@objc static var closeLabel = OEXLocalizedString("ACCESSIBILITY.CLOSE_LABEL", nil)
		@objc static var discussionClosed = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_CLOSED", nil)
		@objc static func discussionFilterBy(filterBy : String) -> String { return OEXLocalizedString("ACCESSIBILITY.DISCUSSION_FILTER_BY", nil).oex_format(withParameters: ["filter_by" : filterBy]) }
		@objc static var discussionFollowed = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_FOLLOWED", nil)
		@objc static var discussionFollowHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_FOLLOW_HINT", nil)
		@objc static func discussionLastPostOn(date : String) -> String { return OEXLocalizedString("ACCESSIBILITY.DISCUSSION_LAST_POST_ON", nil).oex_format(withParameters: ["date" : date]) }
		@objc static var discussionPinned = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_PINNED", nil)
		@objc static func discussionPostedOn(date : String) -> String { return OEXLocalizedString("ACCESSIBILITY.DISCUSSION_POSTED_ON", nil).oex_format(withParameters: ["date" : date]) }
		@objc static var discussionReadThread = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_READ_THREAD", nil)
		@objc static var discussionReportHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_REPORT_HINT", nil)
		@objc static func discussionSortBy(sortBy : String) -> String { return OEXLocalizedString("ACCESSIBILITY.DISCUSSION_SORT_BY", nil).oex_format(withParameters: ["sort_by" : sortBy]) }
		@objc static var discussionThreadHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_THREAD_HINT", nil)
		@objc static var discussionUnfollowHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_UNFOLLOW_HINT", nil)
		@objc static func discussionUnreadReplies(count : String) -> String { return OEXLocalizedString("ACCESSIBILITY.DISCUSSION_UNREAD_REPLIES", nil).oex_format(withParameters: ["count" : count]) }
		@objc static var discussionUnreadThread = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_UNREAD_THREAD", nil)
		@objc static var discussionUnreportHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_UNREPORT_HINT", nil)
		@objc static var discussionUnvoteHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_UNVOTE_HINT", nil)
		@objc static var discussionVoteHint = OEXLocalizedString("ACCESSIBILITY.DISCUSSION_VOTE_HINT", nil)
		@objc static var downloadingVideosTitle = OEXLocalizedString("ACCESSIBILITY.DOWNLOADING_VIDEOS_TITLE", nil)
		@objc static var errorText = OEXLocalizedString("ACCESSIBILITY.ERROR_TEXT", nil)
		@objc static var optionalInput = OEXLocalizedString("ACCESSIBILITY.OPTIONAL_INPUT", nil)
		@objc static var profileLabel = OEXLocalizedString("ACCESSIBILITY.PROFILE_LABEL", nil)
		@objc static var shareACourse = OEXLocalizedString("ACCESSIBILITY.SHARE_A_COURSE", nil)
		@objc static var showCurrentDownloadsButtonHint = OEXLocalizedString("ACCESSIBILITY.SHOW_CURRENT_DOWNLOADS_BUTTON_HINT", nil)
		@objc static var viewAllSubjectsHint = OEXLocalizedString("ACCESSIBILITY.VIEW_ALL_SUBJECTS_HINT", nil)

	}
	@objc class Accomplishments : NSObject {

		@objc static func shareText(platformName : String) -> String { return OEXLocalizedString("ACCOMPLISHMENTS.SHARE_TEXT", nil).oex_format(withParameters: ["platform_name" : platformName]) }
		@objc static var title = OEXLocalizedString("ACCOMPLISHMENTS.TITLE", nil)

	}
	@objc class Agreement : NSObject {

		@objc static func linkTextEula(platformName : String) -> String { return OEXLocalizedString("AGREEMENT.LINK_TEXT_EULA", nil).oex_format(withParameters: ["platform_name" : platformName]) }
		@objc static var linkTextPrivacyPolicy = OEXLocalizedString("AGREEMENT.LINK_TEXT_PRIVACY_POLICY", nil)
		@objc static func linkTextTos(platformName : String) -> String { return OEXLocalizedString("AGREEMENT.LINK_TEXT_TOS", nil).oex_format(withParameters: ["platform_name" : platformName]) }
		@objc static func text(eula : String, tos : String, privacyPolicy : String) -> String { return OEXLocalizedString("AGREEMENT.TEXT", nil).oex_format(withParameters: ["eula" : eula, "tos" : tos, "privacy_policy" : privacyPolicy]) }
		@objc static var textPrefixSignin = OEXLocalizedString("AGREEMENT.TEXT_PREFIX_SIGNIN", nil)
		@objc static var textPrefixSignup = OEXLocalizedString("AGREEMENT.TEXT_PREFIX_SIGNUP", nil)

	}
	@objc class AppReview : NSObject {

		@objc static var helpUsImprove = OEXLocalizedString("APP_REVIEW.HELP_US_IMPROVE", nil)
		@objc static var maybeLater = OEXLocalizedString("APP_REVIEW.MAYBE_LATER", nil)
		@objc static var messageSubject = OEXLocalizedString("APP_REVIEW.MESSAGE_SUBJECT", nil)
		@objc static var positiveReviewMessage = OEXLocalizedString("APP_REVIEW.POSITIVE_REVIEW_MESSAGE", nil)
		@objc static var rateTheApp = OEXLocalizedString("APP_REVIEW.RATE_THE_APP", nil)
		@objc static var rateTheAppQuestion = OEXLocalizedString("APP_REVIEW.RATE_THE_APP_QUESTION", nil)
		@objc static var ratingControlAccessibilityHint = OEXLocalizedString("APP_REVIEW.RATING_CONTROL_ACCESSIBILITY_HINT", nil)
		@objc static var ratingControlAccessibilityLabel = OEXLocalizedString("APP_REVIEW.RATING_CONTROL_ACCESSIBILITY_LABEL", nil)
		@objc static var sendFeedback = OEXLocalizedString("APP_REVIEW.SEND_FEEDBACK", nil)
		@objc static var sendFeedbackTitle = OEXLocalizedString("APP_REVIEW.SEND_FEEDBACK_TITLE", nil)
		@objc static var submit = OEXLocalizedString("APP_REVIEW.SUBMIT", nil)

	}
	@objc class Certificates : NSObject {

		@objc static var courseCompletionSubtitle = OEXLocalizedString("CERTIFICATES.COURSE_COMPLETION_SUBTITLE", nil)
		@objc static var courseCompletionTitle = OEXLocalizedString("CERTIFICATES.COURSE_COMPLETION_TITLE", nil)
		@objc static var getCertificate = OEXLocalizedString("CERTIFICATES.GET_CERTIFICATE", nil)
		@objc static func shareText(platformName : String) -> String { return OEXLocalizedString("CERTIFICATES.SHARE_TEXT", nil).oex_format(withParameters: ["platform_name" : platformName]) }
		@objc static var viewCertTitle = OEXLocalizedString("CERTIFICATES.VIEW_CERT_TITLE", nil)

	}
	@objc class Coursedates : NSObject {

		@objc static var courseDateUnavailable = OEXLocalizedString("COURSEDATES.COURSE_DATE_UNAVAILABLE", nil)
		@objc static var courseImportantDatesTitle = OEXLocalizedString("COURSEDATES.COURSE_IMPORTANT_DATES_TITLE", nil)

	}
	@objc class CourseDetail : NSObject {

		@objc static var effort = OEXLocalizedString("COURSE_DETAIL.EFFORT", nil)
		@objc static var endDate = OEXLocalizedString("COURSE_DETAIL.END_DATE", nil)
		@objc static var enrollNow = OEXLocalizedString("COURSE_DETAIL.ENROLL_NOW", nil)
		@objc static var invitationOnly = OEXLocalizedString("COURSE_DETAIL.INVITATION_ONLY", nil)
		@objc static var viewCourse = OEXLocalizedString("COURSE_DETAIL.VIEW_COURSE", nil)

	}
	@objc class Dashboard : NSObject {

		@objc static var courseAnnouncements = OEXLocalizedString("DASHBOARD.COURSE_ANNOUNCEMENTS", nil)
		@objc static var courseAnnouncementsDetail = OEXLocalizedString("DASHBOARD.COURSE_ANNOUNCEMENTS_DETAIL", nil)
		@objc static var courseCourseware = OEXLocalizedString("DASHBOARD.COURSE_COURSEWARE", nil)
		@objc static var courseCourseDetail = OEXLocalizedString("DASHBOARD.COURSE_COURSE_DETAIL", nil)
		@objc static var courseDiscussion = OEXLocalizedString("DASHBOARD.COURSE_DISCUSSION", nil)
		@objc static var courseDiscussionDetail = OEXLocalizedString("DASHBOARD.COURSE_DISCUSSION_DETAIL", nil)
		@objc static var courseHandouts = OEXLocalizedString("DASHBOARD.COURSE_HANDOUTS", nil)
		@objc static var courseHandoutsDetail = OEXLocalizedString("DASHBOARD.COURSE_HANDOUTS_DETAIL", nil)
		@objc static var courseImportantDates = OEXLocalizedString("DASHBOARD.COURSE_IMPORTANT_DATES", nil)
		@objc static var courseImportantDatesDetail = OEXLocalizedString("DASHBOARD.COURSE_IMPORTANT_DATES_DETAIL", nil)
		@objc static var courseVideos = OEXLocalizedString("DASHBOARD.COURSE_Videos", nil)
		@objc static var courseVideosDetail = OEXLocalizedString("DASHBOARD.COURSE_Videos_DETAIL", nil)

	}
	@objc class Discovery : NSObject {

		@objc static var browseBySubject = OEXLocalizedString("DISCOVERY.BROWSE_BY_SUBJECT", nil)
		@objc static var subjectSearchBarPlaceholder = OEXLocalizedString("DISCOVERY.SUBJECT_SEARCH_BAR_PLACEHOLDER", nil)
		@objc static var viewAllSubjects = OEXLocalizedString("DISCOVERY.VIEW_ALL_SUBJECTS", nil)

	}
	@objc class Discussions : NSObject {

		@objc static func lastPost(date : String) -> String { return OEXLocalizedString("DISCUSSIONS.LAST_POST", nil).oex_format(withParameters: ["date" : date]) }
		@objc static func repliesCount(count : String) -> String { return OEXLocalizedString("DISCUSSIONS.REPLIES_COUNT", nil).oex_format(withParameters: ["count" : count]) }

	}
	@objc class EnrollmentList : NSObject {

		@objc static var findCourses = OEXLocalizedString("ENROLLMENT_LIST.FIND_COURSES", nil)
		@objc static var findCoursesPrompt = OEXLocalizedString("ENROLLMENT_LIST.FIND_COURSES_PROMPT", nil)
		@objc static var noEnrollment = OEXLocalizedString("ENROLLMENT_LIST.NO_ENROLLMENT", nil)

	}
	@objc class ErrorMessage : NSObject {

		@objc static var invalidEmailFormat = OEXLocalizedString("ERROR_MESSAGE.INVALID_EMAIL_FORMAT", nil)

	}
	@objc class Profile : NSObject {

		@objc static var ageLimit = OEXLocalizedString("PROFILE.AGE_LIMIT", nil)
		@objc static var changePictureAccessibilityHint = OEXLocalizedString("PROFILE.CHANGE_PICTURE_ACCESSIBILITY_HINT", nil)
		@objc static var changePictureButton = OEXLocalizedString("PROFILE.CHANGE_PICTURE_BUTTON", nil)
		@objc static var chooseExisting = OEXLocalizedString("PROFILE.CHOOSE_EXISTING", nil)
		@objc static var countryAccessibilityHint = OEXLocalizedString("PROFILE.COUNTRY_ACCESSIBILITY_HINT", nil)
		@objc static var cropAndResizePicture = OEXLocalizedString("PROFILE.CROP_AND_RESIZE_PICTURE", nil)
		@objc static var currentLanguageLabel = OEXLocalizedString("PROFILE.CURRENT_LANGUAGE_LABEL", nil)
		@objc static var currentLocationLabel = OEXLocalizedString("PROFILE.CURRENT_LOCATION_LABEL", nil)
		@objc static var editAccessibility = OEXLocalizedString("PROFILE.EDIT_ACCESSIBILITY", nil)
		@objc static var editTitle = OEXLocalizedString("PROFILE.EDIT_TITLE", nil)
		@objc static var languageAccessibilityHint = OEXLocalizedString("PROFILE.LANGUAGE_ACCESSIBILITY_HINT", nil)
		@objc static func learnerHasLimitedProfile(platformName : String) -> String { return OEXLocalizedString("PROFILE.LEARNER_HAS_LIMITED_PROFILE", nil).oex_format(withParameters: ["platform_name" : platformName]) }
		@objc static var noBio = OEXLocalizedString("PROFILE.NO_BIO", nil)
		@objc static var removeImage = OEXLocalizedString("PROFILE.REMOVE_IMAGE", nil)
		@objc static var showingLimited = OEXLocalizedString("PROFILE.SHOWING_LIMITED", nil)
		@objc static var takePicture = OEXLocalizedString("PROFILE.TAKE_PICTURE", nil)
		@objc static var unableToGet = OEXLocalizedString("PROFILE.UNABLE_TO_GET", nil)
		@objc static var unableToRemovePhoto = OEXLocalizedString("PROFILE.UNABLE_TO_REMOVE_PHOTO", nil)
		@objc static func unableToSend(fieldName : String) -> String { return OEXLocalizedString("PROFILE.UNABLE_TO_SEND", nil).oex_format(withParameters: ["field_name" : fieldName]) }
		@objc static var unableToSetPhoto = OEXLocalizedString("PROFILE.UNABLE_TO_SET_PHOTO", nil)

	}
	@objc class Startup : NSObject {

		@objc static var createYourAccountText = OEXLocalizedString("STARTUP.CREATE_YOUR_ACCOUNT_TEXT", nil)
		@objc static var infoMessageText = OEXLocalizedString("STARTUP.INFO_MESSAGE_TEXT", nil)
		@objc static var loginText = OEXLocalizedString("STARTUP.LOGIN_TEXT", nil)
		@objc static var searchPlaceholderText = OEXLocalizedString("STARTUP.SEARCH_PLACEHOLDER_TEXT", nil)

	}
	@objc class SubmitFeedback : NSObject {

		@objc static func appVersion(version : String, build : String) -> String { return OEXLocalizedString("SUBMIT_FEEDBACK.APP_VERSION", nil).oex_format(withParameters: ["version" : version, "build" : build]) }
		@objc static func deviceModel(model : String) -> String { return OEXLocalizedString("SUBMIT_FEEDBACK.DEVICE_MODEL", nil).oex_format(withParameters: ["model" : model]) }
		@objc static var marker = OEXLocalizedString("SUBMIT_FEEDBACK.MARKER", nil)
		@objc static var messageSubject = OEXLocalizedString("SUBMIT_FEEDBACK.MESSAGE_SUBJECT", nil)
		@objc static var optionTitle = OEXLocalizedString("SUBMIT_FEEDBACK.OPTION_TITLE", nil)
		@objc static func osVersion(version : String) -> String { return OEXLocalizedString("SUBMIT_FEEDBACK.OS_VERSION", nil).oex_format(withParameters: ["version" : version]) }

	}
	@objc class UserAccount : NSObject {

		@objc static var profile = OEXLocalizedString("USER_ACCOUNT.PROFILE", nil)

	}
	@objc class VersionUpgrade : NSObject {

		@objc static var deprecatedMessage = OEXLocalizedString("VERSION_UPGRADE.DEPRECATED_MESSAGE", nil)
		@objc static var dismiss = OEXLocalizedString("VERSION_UPGRADE.DISMISS", nil)
		@objc static var newVersionAvailable = OEXLocalizedString("VERSION_UPGRADE.NEW_VERSION_AVAILABLE", nil)
		@objc static var outDatedMessage = OEXLocalizedString("VERSION_UPGRADE.OUT_DATED_MESSAGE", nil)

	}
	@objc class Video : NSObject {

		@objc static var onlyOnYoutube = OEXLocalizedString("VIDEO.ONLY_ON_YOUTUBE", nil)
		@objc static var viewOnYoutube = OEXLocalizedString("VIDEO.VIEW_ON_YOUTUBE", nil)

	}
	@objc class WhatsNew : NSObject {

		@objc static var done = OEXLocalizedString("WHATS_NEW.DONE", nil)
		@objc static func headerText(appVersion : String) -> String { return OEXLocalizedString("WHATS_NEW.HEADER_TEXT", nil).oex_format(withParameters: ["app_version" : appVersion]) }

	}


	@objc static var acceptLargeVideoDownload = OEXLocalizedString("ACCEPT_LARGE_VIDEO_DOWNLOAD", nil)
	@objc static var accessibilityBy = OEXLocalizedString("ACCESSIBILITY_BY", nil)
	@objc static var accessibilityCheckboxChecked = OEXLocalizedString("ACCESSIBILITY_CHECKBOX_CHECKED", nil)
	@objc static var accessibilityCheckboxHintChecked = OEXLocalizedString("ACCESSIBILITY_CHECKBOX_HINT_CHECKED", nil)
	@objc static var accessibilityCheckboxHintUnchecked = OEXLocalizedString("ACCESSIBILITY_CHECKBOX_HINT_UNCHECKED", nil)
	@objc static var accessibilityCheckboxUnchecked = OEXLocalizedString("ACCESSIBILITY_CHECKBOX_UNCHECKED", nil)
	@objc static var accessibilityCloseMenu = OEXLocalizedString("ACCESSIBILITY_CLOSE_MENU", nil)
	@objc static func accessibilityDownloadableVideos(videoCount : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("ACCESSIBILITY_DOWNLOADABLE_VIDEOS", videoCount, nil).oex_format(withParameters: ["video_count": formatted ?? videoCount.description]) }
	@objc static func accessibilityDownloadProgressButton(percentComplete : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("ACCESSIBILITY_DOWNLOAD_PROGRESS_BUTTON", percentComplete, nil).oex_format(withParameters: ["percent_complete": formatted ?? percentComplete.description]) }
	@objc static func accessibilityDownloadViewCell(videoName : String, percentComplete : String) -> ((Int) -> String) { return {pluralizingCount in OEXLocalizedStringPlural("ACCESSIBILITY_DOWNLOAD_VIEW_CELL", pluralizingCount, nil).oex_format(withParameters: ["video_name" : videoName, "percent_complete" : percentComplete]) }}
	@objc static var accessibilityDropdownTrait = OEXLocalizedString("ACCESSIBILITY_DROPDOWN_TRAIT", nil)
	@objc static var accessibilityExitFullscreen = OEXLocalizedString("ACCESSIBILITY_EXIT_FULLSCREEN", nil)
	@objc static var accessibilityFullscreen = OEXLocalizedString("ACCESSIBILITY_FULLSCREEN", nil)
	@objc static var accessibilityHideKeyboard = OEXLocalizedString("ACCESSIBILITY_HIDE_KEYBOARD", nil)
	@objc static var accessibilityHtml = OEXLocalizedString("ACCESSIBILITY_HTML", nil)
	@objc static var accessibilityMenu = OEXLocalizedString("ACCESSIBILITY_MENU", nil)
	@objc static var accessibilityPause = OEXLocalizedString("ACCESSIBILITY_PAUSE", nil)
	@objc static var accessibilityPlay = OEXLocalizedString("ACCESSIBILITY_PLAY", nil)
	@objc static var accessibilityProblem = OEXLocalizedString("ACCESSIBILITY_PROBLEM", nil)
	@objc static var accessibilityRequiredInput = OEXLocalizedString("ACCESSIBILITY_REQUIRED_INPUT", nil)
	@objc static var accessibilityRewind = OEXLocalizedString("ACCESSIBILITY_REWIND", nil)
	@objc static var accessibilityRewindHint = OEXLocalizedString("ACCESSIBILITY_REWIND_HINT", nil)
	@objc static var accessibilitySeekBar = OEXLocalizedString("ACCESSIBILITY_SEEK_BAR", nil)
	@objc static var accessibilitySelectValueHint = OEXLocalizedString("ACCESSIBILITY_SELECT_VALUE_HINT", nil)
	@objc static var accessibilitySettings = OEXLocalizedString("ACCESSIBILITY_SETTINGS", nil)
	@objc static var accessibilityShowsCourseContent = OEXLocalizedString("ACCESSIBILITY_SHOWS_COURSE_CONTENT", nil)
	@objc static var accessibilityShowsDropdownHint = OEXLocalizedString("ACCESSIBILITY_SHOWS_DROPDOWN_HINT", nil)
	@objc static var accessibilityShowUserProfileHint = OEXLocalizedString("ACCESSIBILITY_SHOW_USER_PROFILE_HINT", nil)
	@objc static var accessibilityUnknown = OEXLocalizedString("ACCESSIBILITY_UNKNOWN", nil)
	@objc static var accessibilityUserAvatar = OEXLocalizedString("ACCESSIBILITY_USER_AVATAR", nil)
	@objc static var accessibilityVideo = OEXLocalizedString("ACCESSIBILITY_VIDEO", nil)
	@objc static var addAComment = OEXLocalizedString("ADD_A_COMMENT", nil)
	@objc static var addAResponse = OEXLocalizedString("ADD_A_RESPONSE", nil)
	@objc static var addComment = OEXLocalizedString("ADD_COMMENT", nil)
	@objc static var addPost = OEXLocalizedString("ADD_POST", nil)
	@objc static var addResponse = OEXLocalizedString("ADD_RESPONSE", nil)
	@objc static var addYourPost = OEXLocalizedString("ADD_YOUR_POST", nil)
	@objc static var allow = OEXLocalizedString("ALLOW", nil)
	@objc static func allDownloadingVideosSubTitle(remainingVideosCount : String, remainingVideosSize : String) -> String { return OEXLocalizedString("ALL_DOWNLOADING_VIDEOS_SUB_TITLE", nil).oex_format(withParameters: ["remaining_videos_count" : remainingVideosCount, "remaining_videos_size" : remainingVideosSize]) }
	@objc static var allPosts = OEXLocalizedString("ALL_POSTS", nil)
	@objc static var allVideos = OEXLocalizedString("ALL_VIDEOS", nil)
	@objc static var allVideosDownloadedTitle = OEXLocalizedString("ALL_VIDEOS_DOWNLOADED_TITLE", nil)
	@objc static var announcementUnavailable = OEXLocalizedString("ANNOUNCEMENT_UNAVAILABLE", nil)
	@objc static var anonymous = OEXLocalizedString("ANONYMOUS", nil)
	@objc static var answer = OEXLocalizedString("ANSWER", nil)
	@objc static var answeredQuestion = OEXLocalizedString("ANSWERED_QUESTION", nil)
	@objc static var asteric = OEXLocalizedString("ASTERIC", nil)
	@objc static func authProviderError(authProvider : String, platformName : String) -> String { return OEXLocalizedString("AUTH_PROVIDER_ERROR", nil).oex_format(withParameters: ["auth_provider" : authProvider, "platform_name" : platformName]) }
	@objc static func bulkDownloadVideosSubTitle(count : String, videosSize : String) -> ((Int) -> String) { return {pluralizingCount in OEXLocalizedStringPlural("BULK_DOWNLOAD_VIDEOS_SUB_TITLE", pluralizingCount, nil).oex_format(withParameters: ["count" : count, "videos_size" : videosSize]) }}
	@objc static func byAuthor(authorName : String) -> String { return OEXLocalizedString("BY_AUTHOR", nil).oex_format(withParameters: ["author_name" : authorName]) }
	@objc static func byAuthorLowerCase(authorName : String) -> String { return OEXLocalizedString("BY_AUTHOR_LOWER_CASE", nil).oex_format(withParameters: ["author_name" : authorName]) }
	@objc static var cancel = OEXLocalizedString("CANCEL", nil)
	@objc static var cellularDownloadEnabledMessage = OEXLocalizedString("CELLULAR_DOWNLOAD_ENABLED_MESSAGE", nil)
	@objc static var cellularDownloadEnabledTitle = OEXLocalizedString("CELLULAR_DOWNLOAD_ENABLED_TITLE", nil)
	@objc static var checkConnection = OEXLocalizedString("CHECK_CONNECTION", nil)
	@objc static var choose = OEXLocalizedString("CHOOSE", nil)
	@objc static var chooseATopic = OEXLocalizedString("CHOOSE_A_TOPIC", nil)
	@objc static var close = OEXLocalizedString("CLOSE", nil)
	@objc static func comment(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("COMMENT", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static var comments = OEXLocalizedString("COMMENTS", nil)
	@objc static var commentsClosed = OEXLocalizedString("COMMENTS_CLOSED", nil)
	@objc static func commentsToResponse(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("COMMENTS_TO_RESPONSE", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static var communityTa = OEXLocalizedString("COMMUNITY_TA", nil)
	@objc static func completeRegistrationInfo(service : String, platformName : String) -> String { return OEXLocalizedString("COMPLETE_REGISTRATION_INFO", nil).oex_format(withParameters: ["service" : service, "platform_name" : platformName]) }
	@objc static var completeRegistrationPrompt = OEXLocalizedString("COMPLETE_REGISTRATION_PROMPT", nil)
	@objc static func confirmDeleteMessage(count : Int) -> String { return OEXLocalizedStringPlural("CONFIRM_DELETE_MESSAGE", count, nil) }
	@objc static var confirmDeleteTitle = OEXLocalizedString("CONFIRM_DELETE_TITLE", nil)
	@objc static var courses = OEXLocalizedString("COURSES", nil)
	@objc static var coursewareUnavailable = OEXLocalizedString("COURSEWARE_UNAVAILABLE", nil)
	@objc static var courseAnnouncements = OEXLocalizedString("COURSE_ANNOUNCEMENTS", nil)
	@objc static func courseAnnouncementNotificationBody(courseName : String) -> String { return OEXLocalizedString("COURSE_ANNOUNCEMENT_NOTIFICATION_BODY", nil).oex_format(withParameters: ["course_name" : courseName]) }
	@objc static var courseContentUnknown = OEXLocalizedString("COURSE_CONTENT_UNKNOWN", nil)
	@objc static func courseDueDate(dueDate : String) -> String { return OEXLocalizedString("COURSE_DUE_DATE", nil).oex_format(withParameters: ["due_date" : dueDate]) }
	@objc static func courseDueDateSameDay(dueDate : String, timeZone : String) -> String { return OEXLocalizedString("COURSE_DUE_DATE_SAME_DAY", nil).oex_format(withParameters: ["due_date" : dueDate, "time_zone" : timeZone]) }
	@objc static func courseEnded(endDate : String) -> String { return OEXLocalizedString("COURSE_ENDED", nil).oex_format(withParameters: ["end_date" : endDate]) }
	@objc static func courseEnding(endDate : String) -> String { return OEXLocalizedString("COURSE_ENDING", nil).oex_format(withParameters: ["end_date" : endDate]) }
	@objc static var courseHandouts = OEXLocalizedString("COURSE_HANDOUTS", nil)
	@objc static var courseModeFull = OEXLocalizedString("COURSE_MODE_FULL", nil)
	@objc static var courseModePickerDescription = OEXLocalizedString("COURSE_MODE_PICKER_DESCRIPTION", nil)
	@objc static var courseModeVideo = OEXLocalizedString("COURSE_MODE_VIDEO", nil)
	@objc static var courseNotListed = OEXLocalizedString("COURSE_NOT_LISTED", nil)
	@objc static var courseNotStarted = OEXLocalizedString("COURSE_NOT_STARTED", nil)
	@objc static var courseVideoUnavailable = OEXLocalizedString("COURSE_VIDEO_UNAVAILABLE", nil)
	@objc static func courseWillStartAt(date : String) -> String { return OEXLocalizedString("COURSE_WILL_START_AT", nil).oex_format(withParameters: ["date" : date]) }
	@objc static var createANewPost = OEXLocalizedString("CREATE_A_NEW_POST", nil)
	@objc static var debug = OEXLocalizedString("DEBUG", nil)
	@objc static var delete = OEXLocalizedString("DELETE", nil)
	@objc static var discover = OEXLocalizedString("DISCOVER", nil)
	@objc static var discussion = OEXLocalizedString("DISCUSSION", nil)
	@objc static var discussionCommentPosted = OEXLocalizedString("DISCUSSION_COMMENT_POSTED", nil)
	@objc static var discussionFollow = OEXLocalizedString("DISCUSSION_FOLLOW", nil)
	@objc static var discussionPost = OEXLocalizedString("DISCUSSION_POST", nil)
	@objc static var discussionReport = OEXLocalizedString("DISCUSSION_REPORT", nil)
	@objc static var discussionThreadPosted = OEXLocalizedString("DISCUSSION_THREAD_POSTED", nil)
	@objc static var discussionTopics = OEXLocalizedString("DISCUSSION_TOPICS", nil)
	@objc static var discussionUnfollow = OEXLocalizedString("DISCUSSION_UNFOLLOW", nil)
	@objc static var discussionUnreport = OEXLocalizedString("DISCUSSION_UNREPORT", nil)
	@objc static var download = OEXLocalizedString("DOWNLOAD", nil)
	@objc static var downloaded = OEXLocalizedString("DOWNLOADED", nil)
	@objc static func downloadedManyVideos(videoCount : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("DOWNLOADED_MANY_VIDEOS", videoCount, nil).oex_format(withParameters: ["video_count": formatted ?? videoCount.description]) }
	@objc static var downloading = OEXLocalizedString("DOWNLOADING", nil)
	@objc static var downloading1Video = OEXLocalizedString("DOWNLOADING_1_VIDEO", nil)
	@objc static var downloadingVideosTitle = OEXLocalizedString("DOWNLOADING_VIDEOS_TITLE", nil)
	@objc static var downloads = OEXLocalizedString("DOWNLOADS", nil)
	@objc static func downloadManyVideos(videoCount : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("DOWNLOAD_MANY_VIDEOS", videoCount, nil).oex_format(withParameters: ["video_count": formatted ?? videoCount.description]) }
	@objc static var downloadToDeviceTitle = OEXLocalizedString("DOWNLOAD_TO_DEVICE_TITLE", nil)
	@objc static var doNotAllow = OEXLocalizedString("DO_NOT_ALLOW", nil)
	@objc static var emailAccountNotSetUpMessage = OEXLocalizedString("EMAIL_ACCOUNT_NOT_SET_UP_MESSAGE", nil)
	@objc static var emailAccountNotSetUpTitle = OEXLocalizedString("EMAIL_ACCOUNT_NOT_SET_UP_TITLE", nil)
	@objc static var emailAddressPrompt = OEXLocalizedString("EMAIL_ADDRESS_PROMPT", nil)
	@objc static func emptyResultset(queryString : String) -> String { return OEXLocalizedString("EMPTY_RESULTSET", nil).oex_format(withParameters: ["query_string" : queryString]) }
	@objc static var endorsed = OEXLocalizedString("ENDORSED", nil)
	@objc static var enterEmail = OEXLocalizedString("ENTER_EMAIL", nil)
	@objc static var enterPassword = OEXLocalizedString("ENTER_PASSWORD", nil)
	@objc static var everyone = OEXLocalizedString("EVERYONE", nil)
	@objc static func externalRegistrationBecameLogin(platformName : String, service : String) -> String { return OEXLocalizedString("EXTERNAL_REGISTRATION_BECAME_LOGIN", nil).oex_format(withParameters: ["platform_name" : platformName, "service" : service]) }
	@objc static var facebook = OEXLocalizedString("FACEBOOK", nil)
	@objc static var failedToLoadTopics = OEXLocalizedString("FAILED_TO_LOAD_TOPICS", nil)
	@objc static var findCourses = OEXLocalizedString("FIND_COURSES", nil)
	@objc static var findCoursesAlreadyEnrolledMessage = OEXLocalizedString("FIND_COURSES_ALREADY_ENROLLED_MESSAGE", nil)
	@objc static var findCoursesEnrollmentErrorDescription = OEXLocalizedString("FIND_COURSES_ENROLLMENT_ERROR_DESCRIPTION", nil)
	@objc static var findCoursesEnrollmentErrorTitle = OEXLocalizedString("FIND_COURSES_ENROLLMENT_ERROR_TITLE", nil)
	@objc static var findCoursesEnrollmentSuccessfulMessage = OEXLocalizedString("FIND_COURSES_ENROLLMENT_SUCCESSFUL_MESSAGE", nil)
	@objc static var findCoursesNoAvailableCourses = OEXLocalizedString("FIND_COURSES_NO_AVAILABLE_COURSES", nil)
	@objc static var findCoursesOfflineMessage = OEXLocalizedString("FIND_COURSES_OFFLINE_MESSAGE", nil)
	@objc static func findCoursesUnableToEnrollErrorDescription(platformName : String) -> String { return OEXLocalizedString("FIND_COURSES_UNABLE_TO_ENROLL_ERROR_DESCRIPTION", nil).oex_format(withParameters: ["platform_name" : platformName]) }
	@objc static var floatingErrorLoginTitle = OEXLocalizedString("FLOATING_ERROR_LOGIN_TITLE", nil)
	@objc static var floatingErrorTitle = OEXLocalizedString("FLOATING_ERROR_TITLE", nil)
	@objc static func formLabel(label : String) -> String { return OEXLocalizedString("FORM_LABEL", nil).oex_format(withParameters: ["label" : label]) }
	@objc static var google = OEXLocalizedString("GOOGLE", nil)
	@objc static var graded = OEXLocalizedString("GRADED", nil)
	@objc static var gradedContentWarning = OEXLocalizedString("GRADED_CONTENT_WARNING", nil)
	@objc static var handoutsUnavailable = OEXLocalizedString("HANDOUTS_UNAVAILABLE", nil)
	@objc static var invalidEmailMessage = OEXLocalizedString("INVALID_EMAIL_MESSAGE", nil)
	@objc static var invalidUsernamePassword = OEXLocalizedString("INVALID_USERNAME_PASSWORD", nil)
	@objc static var largeDownloadMessage = OEXLocalizedString("LARGE_DOWNLOAD_MESSAGE", nil)
	@objc static var largeDownloadTitle = OEXLocalizedString("LARGE_DOWNLOAD_TITLE", nil)
	@objc static var lastAccessed = OEXLocalizedString("LAST_ACCESSED", nil)
	@objc static var loginSplashSignIn = OEXLocalizedString("LOGIN_SPLASH_SIGN_IN", nil)
	@objc static var loginSplashSignUp = OEXLocalizedString("LOGIN_SPLASH_SIGN_UP", nil)
	@objc static var logout = OEXLocalizedString("LOGOUT", nil)
	@objc static var markedAnswer = OEXLocalizedString("MARKED_ANSWER", nil)
	@objc static var mostActivity = OEXLocalizedString("MOST_ACTIVITY", nil)
	@objc static var mostVotes = OEXLocalizedString("MOST_VOTES", nil)
	@objc static var mySettings = OEXLocalizedString("MY_SETTINGS", nil)
	@objc static var myVideosTimeLabel = OEXLocalizedString("MY_VIDEOS_TIME_LABEL", nil)
	@objc static var networkNotAvailableMessage = OEXLocalizedString("NETWORK_NOT_AVAILABLE_MESSAGE", nil)
	@objc static var networkNotAvailableMessageTrouble = OEXLocalizedString("NETWORK_NOT_AVAILABLE_MESSAGE_TROUBLE", nil)
	@objc static var networkNotAvailableTitle = OEXLocalizedString("NETWORK_NOT_AVAILABLE_TITLE", nil)
	@objc static var next = OEXLocalizedString("NEXT", nil)
	@objc static var nextUnit = OEXLocalizedString("NEXT_UNIT", nil)
	@objc static var notificationsEnabled = OEXLocalizedString("NOTIFICATIONS_ENABLED", nil)
	@objc static var notApplicable = OEXLocalizedString("NOT_APPLICABLE", nil)
	@objc static var noCourseResults = OEXLocalizedString("NO_COURSE_RESULTS", nil)
	@objc static var noEnrollmentInterstitialBottomLabel = OEXLocalizedString("NO_ENROLLMENT_INTERSTITIAL_BOTTOM_LABEL", nil)
	@objc static var noEnrollmentInterstitialTopLabel = OEXLocalizedString("NO_ENROLLMENT_INTERSTITIAL_TOP_LABEL", nil)
	@objc static var noFollowingResults = OEXLocalizedString("NO_FOLLOWING_RESULTS", nil)
	@objc static var noResultsFound = OEXLocalizedString("NO_RESULTS_FOUND", nil)
	@objc static var noTranscript = OEXLocalizedString("NO_TRANSCRIPT", nil)
	@objc static var noVideosDownloaded = OEXLocalizedString("NO_VIDEOS_DOWNLOADED", nil)
	@objc static func noVideosTryModeSwitcher(modeSwitcher : String) -> String { return OEXLocalizedString("NO_VIDEOS_TRY_MODE_SWITCHER", nil).oex_format(withParameters: ["mode_switcher" : modeSwitcher]) }
	@objc static var noWifiMessage = OEXLocalizedString("NO_WIFI_MESSAGE", nil)
	@objc static var offline = OEXLocalizedString("OFFLINE", nil)
	@objc static var ok = OEXLocalizedString("OK", nil)
	@objc static var openInBrowser = OEXLocalizedString("OPEN_IN_BROWSER", nil)
	@objc static var openInBrowserTitle = OEXLocalizedString("OPEN_IN_BROWSER_TITLE", nil)
	@objc static var orSignInWith = OEXLocalizedString("OR_SIGN_IN_WITH", nil)
	@objc static func parenthesis(text : String) -> String { return OEXLocalizedString("PARENTHESIS", nil).oex_format(withParameters: ["text" : text]) }
	@objc static var passwordTitleText = OEXLocalizedString("PASSWORD_TITLE_TEXT", nil)
	@objc static var pipeSign = OEXLocalizedString("PIPE_SIGN", nil)
	@objc static var playbackCompleteContinue = OEXLocalizedString("PLAYBACK_COMPLETE_CONTINUE", nil)
	@objc static var playbackCompleteContinueCancel = OEXLocalizedString("PLAYBACK_COMPLETE_CONTINUE_CANCEL", nil)
	@objc static var playbackCompleteMessage = OEXLocalizedString("PLAYBACK_COMPLETE_MESSAGE", nil)
	@objc static var playbackCompleteTitle = OEXLocalizedString("PLAYBACK_COMPLETE_TITLE", nil)
	@objc static var post = OEXLocalizedString("POST", nil)
	@objc static var postsImFollowing = OEXLocalizedString("POSTS_IM_FOLLOWING", nil)
	@objc static var postDiscussion = OEXLocalizedString("POST_DISCUSSION", nil)
	@objc static var postQuestion = OEXLocalizedString("POST_QUESTION", nil)
	@objc static func postVisibility(cohort : String) -> String { return OEXLocalizedString("POST_VISIBILITY", nil).oex_format(withParameters: ["cohort" : cohort]) }
	@objc static var postVisibilityEveryone = OEXLocalizedString("POST_VISIBILITY_EVERYONE", nil)
	@objc static var previous = OEXLocalizedString("PREVIOUS", nil)
	@objc static var previousUnit = OEXLocalizedString("PREVIOUS_UNIT", nil)
	@objc static var programs = OEXLocalizedString("PROGRAMS", nil)
	@objc static var question = OEXLocalizedString("QUESTION", nil)
	@objc static var recentActivity = OEXLocalizedString("RECENT_ACTIVITY", nil)
	@objc static var recentVideos = OEXLocalizedString("RECENT_VIDEOS", nil)
	@objc static var refine = OEXLocalizedString("REFINE", nil)
	@objc static var registerText = OEXLocalizedString("REGISTER_TEXT", nil)
	@objc static var registrationAgreementMessage = OEXLocalizedString("REGISTRATION_AGREEMENT_MESSAGE", nil)
	@objc static var registrationCreateMyAccount = OEXLocalizedString("REGISTRATION_CREATE_MY_ACCOUNT", nil)
	@objc static var registrationCreatingAccount = OEXLocalizedString("REGISTRATION_CREATING_ACCOUNT", nil)
	@objc static var registrationErrorAlertMessage = OEXLocalizedString("REGISTRATION_ERROR_ALERT_MESSAGE", nil)
	@objc static var registrationErrorAlertTitle = OEXLocalizedString("REGISTRATION_ERROR_ALERT_TITLE", nil)
	@objc static func registrationFieldEmptyError(fieldName : String) -> String { return OEXLocalizedString("REGISTRATION_FIELD_EMPTY_ERROR", nil).oex_format(withParameters: ["field_name" : fieldName]) }
	@objc static func registrationFieldEmptySelectError(fieldName : String) -> String { return OEXLocalizedString("REGISTRATION_FIELD_EMPTY_SELECT_ERROR", nil).oex_format(withParameters: ["field_name" : fieldName]) }
	@objc static func registrationFieldMaxLengthError(fieldName : String, count : String) -> ((Int) -> String) { return {pluralizingCount in OEXLocalizedStringPlural("REGISTRATION_FIELD_MAX_LENGTH_ERROR", pluralizingCount, nil).oex_format(withParameters: ["field_name" : fieldName, "count" : count]) }}
	@objc static func registrationFieldMinLengthError(fieldName : String, count : String) -> ((Int) -> String) { return {pluralizingCount in OEXLocalizedStringPlural("REGISTRATION_FIELD_MIN_LENGTH_ERROR", pluralizingCount, nil).oex_format(withParameters: ["field_name" : fieldName, "count" : count]) }}
	@objc static var registrationHideOptionalFields = OEXLocalizedString("REGISTRATION_HIDE_OPTIONAL_FIELDS", nil)
	@objc static var registrationRegisterAlternatePrompt = OEXLocalizedString("REGISTRATION_REGISTER_ALTERNATE_PROMPT", nil)
	@objc static var registrationRegisterPrompt = OEXLocalizedString("REGISTRATION_REGISTER_PROMPT", nil)
	@objc static var registrationShowOptionalFields = OEXLocalizedString("REGISTRATION_SHOW_OPTIONAL_FIELDS", nil)
	@objc static var reload = OEXLocalizedString("RELOAD", nil)
	@objc static var removeFilter = OEXLocalizedString("REMOVE_FILTER", nil)
	@objc static var resetPasswordConfirmationMessage = OEXLocalizedString("RESET_PASSWORD_CONFIRMATION_MESSAGE", nil)
	@objc static var resetPasswordConfirmationTitle = OEXLocalizedString("RESET_PASSWORD_CONFIRMATION_TITLE", nil)
	@objc static var resetPasswordPopupText = OEXLocalizedString("RESET_PASSWORD_POPUP_TEXT", nil)
	@objc static var resetPasswordTitle = OEXLocalizedString("RESET_PASSWORD_TITLE", nil)
	@objc static var resourses = OEXLocalizedString("RESOURSES", nil)
	@objc static func response(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("RESPONSE", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static var responsesClosed = OEXLocalizedString("RESPONSES_CLOSED", nil)
	@objc static var retry = OEXLocalizedString("RETRY", nil)
	@objc static var rotateDevice = OEXLocalizedString("ROTATE_DEVICE", nil)
	@objc static var searchAllPosts = OEXLocalizedString("SEARCH_ALL_POSTS", nil)
	@objc static var searchResults = OEXLocalizedString("SEARCH_RESULTS", nil)
	@objc static var sectionUnavailableOffline = OEXLocalizedString("SECTION_UNAVAILABLE_OFFLINE", nil)
	@objc static func serviceAccountNotAssociatedMessage(service : String, platformName : String, destinationName : String) -> String { return OEXLocalizedString("SERVICE_ACCOUNT_NOT_ASSOCIATED_MESSAGE", nil).oex_format(withParameters: ["service" : service, "platform_name" : platformName, "destination_name" : destinationName]) }
	@objc static func serviceAccountNotAssociatedTitle(service : String, platformName : String) -> String { return OEXLocalizedString("SERVICE_ACCOUNT_NOT_ASSOCIATED_TITLE", nil).oex_format(withParameters: ["service" : service, "platform_name" : platformName]) }
	@objc static var settings = OEXLocalizedString("SETTINGS", nil)
	@objc static func shareACourse(platformName : String) -> String { return OEXLocalizedString("SHARE_A_COURSE", nil).oex_format(withParameters: ["platform_name" : platformName]) }
	@objc static var signInButtonTextOnSignIn = OEXLocalizedString("SIGN_IN_BUTTON_TEXT_ON_SIGN_IN", nil)
	@objc static var signInText = OEXLocalizedString("SIGN_IN_TEXT", nil)
	@objc static var soon = OEXLocalizedString("SOON", nil)
	@objc static var staff = OEXLocalizedString("STAFF", nil)
	@objc static func starting(startDate : String) -> String { return OEXLocalizedString("STARTING", nil).oex_format(withParameters: ["start_date" : startDate]) }
	@objc static var startupExploreSubjects = OEXLocalizedString("STARTUP_EXPLORE_SUBJECTS", nil)
	@objc static var timeoutAlertTitle = OEXLocalizedString("TIMEOUT_ALERT_TITLE", nil)
	@objc static var timeoutCheckInternetConnection = OEXLocalizedString("TIMEOUT_CHECK_INTERNET_CONNECTION", nil)
	@objc static var title = OEXLocalizedString("TITLE", nil)
	@objc static func topic(topic : String) -> String { return OEXLocalizedString("TOPIC", nil).oex_format(withParameters: ["topic" : topic]) }
	@objc static var topics = OEXLocalizedString("TOPICS", nil)
	@objc static var troubleInLoginButton = OEXLocalizedString("TROUBLE_IN_LOGIN_BUTTON", nil)
	@objc static var unableToDownload = OEXLocalizedString("UNABLE_TO_DOWNLOAD", nil)
	@objc static var unableToLoadCourseContent = OEXLocalizedString("UNABLE_TO_LOAD_COURSE_CONTENT", nil)
	@objc static var unanswered = OEXLocalizedString("UNANSWERED", nil)
	@objc static var unansweredQuestion = OEXLocalizedString("UNANSWERED_QUESTION", nil)
	@objc static var unknownError = OEXLocalizedString("UNKNOWN_ERROR", nil)
	@objc static var unread = OEXLocalizedString("UNREAD", nil)
	@objc static var untitled = OEXLocalizedString("UNTITLED", nil)
	@objc static var usernameTitleText = OEXLocalizedString("USERNAME_TITLE_TEXT", nil)
	@objc static var userAccount = OEXLocalizedString("USER_ACCOUNT", nil)
	@objc static func versionDisplay(number : String, environment : String) -> String { return OEXLocalizedString("VERSION_DISPLAY", nil).oex_format(withParameters: ["number" : number, "environment" : environment]) }
	@objc static var versionUpgradeOutDatedLoginMessage = OEXLocalizedString("VERSION_UPGRADE_OUT_DATED_LOGIN_MESSAGE", nil)
	@objc static var versionUpgradeUpdate = OEXLocalizedString("VERSION_UPGRADE_UPDATE", nil)
	@objc static func videosDeleted(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("VIDEOS_DELETED", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static func videosDownloaded(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("VIDEOS_DOWNLOADED", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static func videosDownloading(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("VIDEOS_DOWNLOADING", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static var videoContentNotAvailable = OEXLocalizedString("VIDEO_CONTENT_NOT_AVAILABLE", nil)
	@objc static var videoDownloadsInProgress = OEXLocalizedString("VIDEO_DOWNLOADS_IN_PROGRESS", nil)
	@objc static var videoNotAvailable = OEXLocalizedString("VIDEO_NOT_AVAILABLE", nil)
	@objc static var videoOnlyOnWeb = OEXLocalizedString("VIDEO_ONLY_ON_WEB", nil)
	@objc static var videoPlayerDefaultRemainingTime = OEXLocalizedString("VIDEO_PLAYER_DEFAULT_REMAINING_TIME", nil)
	@objc static var videoSettingSelected = OEXLocalizedString("VIDEO_SETTING_SELECTED", nil)
	@objc static var view = OEXLocalizedString("VIEW", nil)
	@objc static var viewHandouts = OEXLocalizedString("VIEW_HANDOUTS", nil)
	@objc static func vote(count : Int, formatted : String? = nil) -> String { return OEXLocalizedStringPlural("VOTE", count, nil).oex_format(withParameters: ["count": formatted ?? count.description]) }
	@objc static var waitingForResponse = OEXLocalizedString("WAITING_FOR_RESPONSE", nil)
	@objc static var wifiOnlyDetailMessage = OEXLocalizedString("WIFI_ONLY_DETAIL_MESSAGE", nil)
	@objc static var wifiOnlyTitle = OEXLocalizedString("WIFI_ONLY_TITLE", nil)
	@objc static var yes = OEXLocalizedString("YES", nil)

}

